version: '2'
services:
  db:
    image: neo4j:3.0
    environment:
      - NEO4J_AUTH=neo4j/openbeer
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    volumes:
      - db-data:/data

volumes:
  db-data: {}
